version: "3.8"
services:
  database:
    image: postgres
    container_name: postgres_3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sahil
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /Users/appayevs/Desktop/Code_project/volumes/postgres_2:/var/lib/postgresql/data
