version: "3.8"
services:
  database:
    image: postgres
    container_name: postgres_2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sahil
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /Users/appayevs/Desktop/Code_project/volumes/postgres_2:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: mypassword

