spring:
  application:
    name: ms-product

  datasource:
    username: sahil
    password: mypassword
    url: jdbc:postgresql://127.0.0.1:5433/postgres
  jpa:
    open-in-view: false

  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 1500
            read-timeout: 2000
            logger-level: basic

logging:
  level:
    root: info

springdoc:
  api-docs:
    version: openapi_3_0

server:
  port: 8083

api:
  ms-account:
    url: http://127.0.0.1:8082

