spring:
  application:
    name: Booking App

  datasource:
    username: sahil
    password: mypassword
    url: jdbc:postgresql://127.0.0.1:5433/postgres

  liquibase:
    enabled: true
#  jpa:
#    open-in-view: false

logging:
  level:
    root: info

server:
  port: 8088
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /test-ui

minio:
  url: http://127.0.0.1:9000/
  bucket: booking
  access-key: bookingUser
  secret-key: bookingSecret
  image-folder: image/
  video-folder: video/
  document-folder: document/

file:
  upload:
    acceptableVideoExtensions: mp4,mov,avi,wmv
    acceptableImageExtensions: jpg,png,jpeg
    acceptablePdfExtensions: pdf