spring:
  application:
    name: Booking App

  datasource:
    username: sahil
    password: mypassword
    url: jdbc:postgresql://127.0.0.1:5433/postgres

  liquibase:
    enabled: true
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          cat:
            connect-timeout: 1500
            read-timeout: 2000
            logger-level: basic
#            error-decoder: org.mn.booking.client.CatErrorDecoder
#
#          default:
#            connectTimeout: 1000
#            readTimeout: 3000
#            loggerLevel: full

#  jpa:
#    open-in-view: false

#  security:
#    user:
#      name: ali
#      password: 12345

logging:
  level:
    root: info

server:
  port: 8088
#  servlet:
#    context-path: /api

#springdoc:
#  swagger-ui:
#    path: /test-ui

minio:
  url: http://127.0.0.1:9000/
  bucket: booking
  access-key: bookingUser
  secret-key: bookingSecret
  image-folder: image/
  video-folder: video/
  document-folder: document/

file:
  upload:
    acceptableVideoExtensions: mp4,mov,avi,wmv
    acceptableImageExtensions: jpg,png,jpeg
    acceptablePdfExtensions: pdf

jwt:
  refresh:
    ttl: 5
    secret-key: eff1efd57b47cb789ab0013c2d4e3ea4d6c18eadf45cc69c4f58ccc704254f455e5c9e35da7a7ef5bee907e89a9c6fa875bcf4ba1fe483f57a6f3dbe6235f8e8f2c63e89894265537bd1a7cb000e98d1382d6d888ef0c6b3f73a6e47d1ed236865899f0c02244abb53ba0f5ad83769106cea15df48ded552c8d824ffe2eaeca8
  access:
    ttl: 2
    secret-key: ef2a9ed1f716d5b7f0fc68b992714ec2feccf145f88ef79f8b3dc77f6a549eea75df2848046b819810446667d290815363ab481b5d0cfc4c2094d5989a5c58168b489a462f09fbdfa523e3418d530d2c567fdac656834f0dc832ba87e9a2d5c4558db3ececae4bf701c6723c9b417af6043f0cdd94b2ed016f1fa2bf8f33f23a


scheduler:
  default:
    lockAtMost: 1H
  printOrders:
    lockAtLeast: 15S
    lockAtMost: 30M


api:
  cat:
    url: https://catfact.ninja


