spring:
  application:
    name: Booking App

  datasource:
    username: sahil
    password: mypassword
    url: jdbc:postgresql://127.0.0.1:5433/postgres

  liquibase:
    enabled: true

logging:
  level:
    root: info